# Generated by Django 5.2.5 on 2025-09-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryUsers', '0001_initial'),
        ('Library_BookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_BookStore.booksnames')),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_BookStore.booksautors_names')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryUsers.libraryusers')),
            ],
        ),
    ]
